### ISSUE TITLE
Maybe use ION for the DID/PKI part?

### ISSUE THREAD

**Issue by earonesty** [TBDev-54566975/white-paper#11]
PKI can be handled nicely by the existing, production-ready https://github.com/decentralized-identity/ion .   

Seems to handle everything you need in the whitepaper, and should get this thing rolling sooner.  IE: you can publish to it & build on it, rather than starting from scratch.

**Comment by csuwildcat** [comment]
The protocol will be designed to be pluggable, allowing for future additions, but this will be the default DID Method. Any future additions will be evaluated if/when needs or requirements arise to justify it. Closing as completed.

**Comment by ravibala1** [comment]
Just looking at the link to the ION GitHub page and it references Bitcoin specifically. Is there value in making clear at the outset of the protocol that in the future it will need to be cross-chain explicitly?
